# Generated by Django 5.1.5 on 2025-01-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('creation_date', models.DateField()),
                ('deadline', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DurationField()),
            ],
        ),
    ]
