# Generated by Django 5.1.5 on 2025-01-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionsnobjectives', '0002_alter_objective_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='completion_date',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
